spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    locations: classpath:db/migration/psql,classpath:db/migration/common
  datasource:
    url: jdbc:postgresql://192.168.1.99:5432/trading
    username: postgres
    password: root
    hikari:
#      transaction-isolation: TRANSACTION_READ_COMMITTED
#      transaction-isolation: TRANSACTION_REPEATABLE_READ
      transaction-isolation: TRANSACTION_SERIALIZABLE
