spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration/psql,classpath:db/migration/common
  datasource:
    url: jdbc:postgresql://localhost:5432/trading
    username: postgres
    password: root
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE
